# either set server.port as system property using command line option to jvm -Dserver.port=6583
# java -Dserver.port=6583 -jar target/activity-server-1.0.jar
# java -jar target/activity-server-1.0.jar --server.port=6583
server:
  port: 8081
  servlet:
    contextPath: /rain-server
  error:
    whitelabel:
      enabled: false

spring:
  redis:
    database: 1 # Redis数据库索引（默认为0）,如果设置为1，那么存入的key-value都存放在select 1中
    host: 127.0.0.1
    port: 6379
    max-wait: 30000    # 连接池最大阻塞等待时间（使用负值表示没有限制）
    max-active: 100   # 连接池最大连接数（使用负值表示没有限制）
    max-idle: 20     # 连接池中的最大空闲连接
    min-idle: 0     # 连接池中的最小空闲连接
    timeout: 5000   # 连接超时
      #password: 123456 # 密码,默认密码为空
      #cluster:       # 集群配置
      #nodes: 127.0.0.1:6381,127.0.0.1:6382,127.0.0.1:6383,127.0.0.1:6384,127.0.0.1:6385,127.0.0.1:6386
    #max-redirects: 2  # 最大重定向次数